version: "3.9"
services:
   nginx:
     build: ./nginx/
     ports:
       - 80:80
  
     volumes:
         - ./php/:/var/www/html/

   php:
     build: ./php_code/
     expose:
       - 8010
     volumes:
        - ./php/:/var/www/html/